### ISSUE TITLE
Intrinsic and Extrinsic Parameter for Oxford Dataset

### ISSUE THREAD

**Issue by joomeok** [petrhruby97/efficient_absolute#1]
From the ~.P file of each data set, I could not achieve the right result after decomposing these matrices to obtain intrinsic and extrinsic matrices.

To be specific, the intrinsic matrix of each scene is completely different. Can you give me some information or instructions for doing this? I would greatly appreciate your help.

**Comment by petrhruby97** [comment]
You can decompose the matrix using RQ decomposition of the left 3x3 submatrix. Using this, the submatrix will be decomposed into a diagonal intrinsic matrix and an orthogonal rotation matrix. Then, you can obtain the translation vector by multiplying the right 3x1 submatrix of the projection matrix with the intrinsic matrix.

This decomposition is performed in the script "[text_oxford_dataset.py](https://github.com/petrhruby97/efficient_absolute/blob/main/text_oxford_dataset.py)". Running this script is the easiest way to test the method. In the script, we perform the following steps to decompose the projection matrix.

First, we load the ~.P file in python as

    P = np.loadtxt("~.P")

Then, we get the intrinsic matrix K and rotation matrix R as (L225-L227)

       K0,R = linalg.rq(P[:,0:3])
       K = K0/K0[2,2]
       P = P/K0[2,2]

If some diagonal elements of K are negative we construct a correction matrix cor, and use it to simultaneously swap the signs of the columns of K and rows of R. Note, that the product K*R is not changed by this (L231-L237):

        cor = np.eye(3)
        if K[0,0] < 0:
            cor[0,0] = -1
        if K[1,1] < 0:
            cor[1,1] = -1
        K = K@cor
        R = cor@R

Then, we find the translation vector t, and the intrinsic matrix Pc, as: (L239-L241)
        Ki = linalg.inv(K)
        t = Ki @ P[:,3]
        Pc = Ki @ P

Finally, if the determinant of matrix R is -1, we multiply it with -1, and then:
a) for the wadham sequence also multiply t with -1
b) for all other sequences multiply the 3D points with -1
This is done on lines 243-250:

        if np.linalg.det(R) < 0:
            R = -1*R
            if seq=='wadham':
                t = -1*t
            else:
                pt_3D = -1*pt_3D
                X1_3D = -1*X1_3D
                X2_3D = -1*X2_3D

**Comment by joomeok** [comment]
Thank you for reply!
